/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as TodoRouteImport } from './routes/todo'
import { Route as CoursesIndexRouteImport } from './routes/courses.index'
import { Route as CoursesCourseIdRouteImport } from './routes/courses.$courseId'
import { Route as ApiTrpcSplatRouteImport } from './routes/api.trpc.$'
import { Route as CoursesCourseIdIndexRouteImport } from './routes/courses.$courseId.index'
import { Route as CoursesCourseIdAnnouncementsRouteImport } from './routes/courses.$courseId.announcements'
import { Route as CoursesCourseIdAssignmentsRouteImport } from './routes/courses.$courseId.assignments'
import { Route as CoursesCourseIdDiscussionsRouteImport } from './routes/courses.$courseId.discussions'
import { Route as CoursesCourseIdFilesRouteImport } from './routes/courses.$courseId.files'
import { Route as CoursesCourseIdGradesRouteImport } from './routes/courses.$courseId.grades'
import { Route as CoursesCourseIdModulesRouteImport } from './routes/courses.$courseId.modules'
import { Route as CoursesCourseIdPagesRouteImport } from './routes/courses.$courseId.pages'
import { Route as CoursesCourseIdQuizzesRouteImport } from './routes/courses.$courseId.quizzes'
import { Route as CoursesCourseIdSyllabusRouteImport } from './routes/courses.$courseId.syllabus'
import { Route as CoursesCourseIdUsersRouteImport } from './routes/courses.$courseId.users'
import { Route as CoursesCourseIdAssignmentsAssignmentIdRouteImport } from './routes/courses.$courseId.assignments_.$assignmentId'
import { Route as CoursesCourseIdDiscussionsTopicIdRouteImport } from './routes/courses.$courseId.discussions_.$topicId'
import { Route as CoursesCourseIdFilesFileIdRouteImport } from './routes/courses.$courseId.files_.$fileId'
import { Route as CoursesCourseIdPagesPageUrlRouteImport } from './routes/courses.$courseId.pages_.$pageUrl'
import { Route as CoursesCourseIdQuizzesQuizIdRouteImport } from './routes/courses.$courseId.quizzes_.$quizId'
import { Route as CoursesCourseIdToolsTabIdRouteImport } from './routes/courses.$courseId.tools.$tabId'
import { Route as CoursesCourseIdModulesItemsItemIdRouteImport } from './routes/courses.$courseId.modules_.items.$itemId'
import { Route as ApiCanvasCoursesCourseIdFilesFileIdRouteImport } from './routes/api.canvas.courses.$courseId.files.$fileId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const TodoRoute = TodoRouteImport.update({
  id: '/todo',
  path: '/todo',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesIndexRoute = CoursesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CoursesRoute,
} as any)
const CoursesCourseIdRoute = CoursesCourseIdRouteImport.update({
  id: '/$courseId',
  path: '/$courseId',
  getParentRoute: () => CoursesRoute,
} as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesCourseIdIndexRoute = CoursesCourseIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CoursesCourseIdRoute,
} as any)
const CoursesCourseIdAnnouncementsRoute =
  CoursesCourseIdAnnouncementsRouteImport.update({
    id: '/announcements',
    path: '/announcements',
    getParentRoute: () => CoursesCourseIdRoute,
  } as any)
const CoursesCourseIdAssignmentsRoute =
  CoursesCourseIdAssignmentsRouteImport.update({
    id: '/assignments',
    path: '/assignments',
    getParentRoute: () => CoursesCourseIdRoute,
  } as any)
const CoursesCourseIdDiscussionsRoute =
  CoursesCourseIdDiscussionsRouteImport.update({
    id: '/discussions',
    path: '/discussions',
    getParentRoute: () => CoursesCourseIdRoute,
  } as any)
const CoursesCourseIdFilesRoute = CoursesCourseIdFilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => CoursesCourseIdRoute,
} as any)
const CoursesCourseIdGradesRoute = CoursesCourseIdGradesRouteImport.update({
  id: '/grades',
  path: '/grades',
  getParentRoute: () => CoursesCourseIdRoute,
} as any)
const CoursesCourseIdModulesRoute = CoursesCourseIdModulesRouteImport.update({
  id: '/modules',
  path: '/modules',
  getParentRoute: () => CoursesCourseIdRoute,
} as any)
const CoursesCourseIdPagesRoute = CoursesCourseIdPagesRouteImport.update({
  id: '/pages',
  path: '/pages',
  getParentRoute: () => CoursesCourseIdRoute,
} as any)
const CoursesCourseIdQuizzesRoute = CoursesCourseIdQuizzesRouteImport.update({
  id: '/quizzes',
  path: '/quizzes',
  getParentRoute: () => CoursesCourseIdRoute,
} as any)
const CoursesCourseIdSyllabusRoute = CoursesCourseIdSyllabusRouteImport.update({
  id: '/syllabus',
  path: '/syllabus',
  getParentRoute: () => CoursesCourseIdRoute,
} as any)
const CoursesCourseIdUsersRoute = CoursesCourseIdUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => CoursesCourseIdRoute,
} as any)
const CoursesCourseIdAssignmentsAssignmentIdRoute =
  CoursesCourseIdAssignmentsAssignmentIdRouteImport.update({
    id: '/assignments_/$assignmentId',
    path: '/assignments/$assignmentId',
    getParentRoute: () => CoursesCourseIdRoute,
  } as any)
const CoursesCourseIdDiscussionsTopicIdRoute =
  CoursesCourseIdDiscussionsTopicIdRouteImport.update({
    id: '/discussions_/$topicId',
    path: '/discussions/$topicId',
    getParentRoute: () => CoursesCourseIdRoute,
  } as any)
const CoursesCourseIdFilesFileIdRoute =
  CoursesCourseIdFilesFileIdRouteImport.update({
    id: '/files_/$fileId',
    path: '/files/$fileId',
    getParentRoute: () => CoursesCourseIdRoute,
  } as any)
const CoursesCourseIdPagesPageUrlRoute =
  CoursesCourseIdPagesPageUrlRouteImport.update({
    id: '/pages_/$pageUrl',
    path: '/pages/$pageUrl',
    getParentRoute: () => CoursesCourseIdRoute,
  } as any)
const CoursesCourseIdQuizzesQuizIdRoute =
  CoursesCourseIdQuizzesQuizIdRouteImport.update({
    id: '/quizzes_/$quizId',
    path: '/quizzes/$quizId',
    getParentRoute: () => CoursesCourseIdRoute,
  } as any)
const CoursesCourseIdToolsTabIdRoute =
  CoursesCourseIdToolsTabIdRouteImport.update({
    id: '/tools/$tabId',
    path: '/tools/$tabId',
    getParentRoute: () => CoursesCourseIdRoute,
  } as any)
const CoursesCourseIdModulesItemsItemIdRoute =
  CoursesCourseIdModulesItemsItemIdRouteImport.update({
    id: '/modules_/items/$itemId',
    path: '/modules/items/$itemId',
    getParentRoute: () => CoursesCourseIdRoute,
  } as any)
const ApiCanvasCoursesCourseIdFilesFileIdRoute =
  ApiCanvasCoursesCourseIdFilesFileIdRouteImport.update({
    id: '/api/canvas/courses/$courseId/files/$fileId',
    path: '/api/canvas/courses/$courseId/files/$fileId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/courses': typeof CoursesRouteWithChildren
  '/todo': typeof TodoRoute
  '/courses/$courseId': typeof CoursesCourseIdRouteWithChildren
  '/courses/': typeof CoursesIndexRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/courses/$courseId/announcements': typeof CoursesCourseIdAnnouncementsRoute
  '/courses/$courseId/assignments': typeof CoursesCourseIdAssignmentsRoute
  '/courses/$courseId/discussions': typeof CoursesCourseIdDiscussionsRoute
  '/courses/$courseId/files': typeof CoursesCourseIdFilesRoute
  '/courses/$courseId/grades': typeof CoursesCourseIdGradesRoute
  '/courses/$courseId/modules': typeof CoursesCourseIdModulesRoute
  '/courses/$courseId/pages': typeof CoursesCourseIdPagesRoute
  '/courses/$courseId/quizzes': typeof CoursesCourseIdQuizzesRoute
  '/courses/$courseId/syllabus': typeof CoursesCourseIdSyllabusRoute
  '/courses/$courseId/users': typeof CoursesCourseIdUsersRoute
  '/courses/$courseId/': typeof CoursesCourseIdIndexRoute
  '/courses/$courseId/assignments/$assignmentId': typeof CoursesCourseIdAssignmentsAssignmentIdRoute
  '/courses/$courseId/discussions/$topicId': typeof CoursesCourseIdDiscussionsTopicIdRoute
  '/courses/$courseId/files/$fileId': typeof CoursesCourseIdFilesFileIdRoute
  '/courses/$courseId/pages/$pageUrl': typeof CoursesCourseIdPagesPageUrlRoute
  '/courses/$courseId/quizzes/$quizId': typeof CoursesCourseIdQuizzesQuizIdRoute
  '/courses/$courseId/tools/$tabId': typeof CoursesCourseIdToolsTabIdRoute
  '/courses/$courseId/modules/items/$itemId': typeof CoursesCourseIdModulesItemsItemIdRoute
  '/api/canvas/courses/$courseId/files/$fileId': typeof ApiCanvasCoursesCourseIdFilesFileIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/todo': typeof TodoRoute
  '/courses': typeof CoursesIndexRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/courses/$courseId/announcements': typeof CoursesCourseIdAnnouncementsRoute
  '/courses/$courseId/assignments': typeof CoursesCourseIdAssignmentsRoute
  '/courses/$courseId/discussions': typeof CoursesCourseIdDiscussionsRoute
  '/courses/$courseId/files': typeof CoursesCourseIdFilesRoute
  '/courses/$courseId/grades': typeof CoursesCourseIdGradesRoute
  '/courses/$courseId/modules': typeof CoursesCourseIdModulesRoute
  '/courses/$courseId/pages': typeof CoursesCourseIdPagesRoute
  '/courses/$courseId/quizzes': typeof CoursesCourseIdQuizzesRoute
  '/courses/$courseId/syllabus': typeof CoursesCourseIdSyllabusRoute
  '/courses/$courseId/users': typeof CoursesCourseIdUsersRoute
  '/courses/$courseId': typeof CoursesCourseIdIndexRoute
  '/courses/$courseId/assignments/$assignmentId': typeof CoursesCourseIdAssignmentsAssignmentIdRoute
  '/courses/$courseId/discussions/$topicId': typeof CoursesCourseIdDiscussionsTopicIdRoute
  '/courses/$courseId/files/$fileId': typeof CoursesCourseIdFilesFileIdRoute
  '/courses/$courseId/pages/$pageUrl': typeof CoursesCourseIdPagesPageUrlRoute
  '/courses/$courseId/quizzes/$quizId': typeof CoursesCourseIdQuizzesQuizIdRoute
  '/courses/$courseId/tools/$tabId': typeof CoursesCourseIdToolsTabIdRoute
  '/courses/$courseId/modules/items/$itemId': typeof CoursesCourseIdModulesItemsItemIdRoute
  '/api/canvas/courses/$courseId/files/$fileId': typeof ApiCanvasCoursesCourseIdFilesFileIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/courses': typeof CoursesRouteWithChildren
  '/todo': typeof TodoRoute
  '/courses/$courseId': typeof CoursesCourseIdRouteWithChildren
  '/courses/': typeof CoursesIndexRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/courses/$courseId/announcements': typeof CoursesCourseIdAnnouncementsRoute
  '/courses/$courseId/assignments': typeof CoursesCourseIdAssignmentsRoute
  '/courses/$courseId/discussions': typeof CoursesCourseIdDiscussionsRoute
  '/courses/$courseId/files': typeof CoursesCourseIdFilesRoute
  '/courses/$courseId/grades': typeof CoursesCourseIdGradesRoute
  '/courses/$courseId/modules': typeof CoursesCourseIdModulesRoute
  '/courses/$courseId/pages': typeof CoursesCourseIdPagesRoute
  '/courses/$courseId/quizzes': typeof CoursesCourseIdQuizzesRoute
  '/courses/$courseId/syllabus': typeof CoursesCourseIdSyllabusRoute
  '/courses/$courseId/users': typeof CoursesCourseIdUsersRoute
  '/courses/$courseId/': typeof CoursesCourseIdIndexRoute
  '/courses/$courseId/assignments_/$assignmentId': typeof CoursesCourseIdAssignmentsAssignmentIdRoute
  '/courses/$courseId/discussions_/$topicId': typeof CoursesCourseIdDiscussionsTopicIdRoute
  '/courses/$courseId/files_/$fileId': typeof CoursesCourseIdFilesFileIdRoute
  '/courses/$courseId/pages_/$pageUrl': typeof CoursesCourseIdPagesPageUrlRoute
  '/courses/$courseId/quizzes_/$quizId': typeof CoursesCourseIdQuizzesQuizIdRoute
  '/courses/$courseId/tools/$tabId': typeof CoursesCourseIdToolsTabIdRoute
  '/courses/$courseId/modules_/items/$itemId': typeof CoursesCourseIdModulesItemsItemIdRoute
  '/api/canvas/courses/$courseId/files/$fileId': typeof ApiCanvasCoursesCourseIdFilesFileIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calendar'
    | '/courses'
    | '/todo'
    | '/courses/$courseId'
    | '/courses/'
    | '/api/trpc/$'
    | '/courses/$courseId/announcements'
    | '/courses/$courseId/assignments'
    | '/courses/$courseId/discussions'
    | '/courses/$courseId/files'
    | '/courses/$courseId/grades'
    | '/courses/$courseId/modules'
    | '/courses/$courseId/pages'
    | '/courses/$courseId/quizzes'
    | '/courses/$courseId/syllabus'
    | '/courses/$courseId/users'
    | '/courses/$courseId/'
    | '/courses/$courseId/assignments/$assignmentId'
    | '/courses/$courseId/discussions/$topicId'
    | '/courses/$courseId/files/$fileId'
    | '/courses/$courseId/pages/$pageUrl'
    | '/courses/$courseId/quizzes/$quizId'
    | '/courses/$courseId/tools/$tabId'
    | '/courses/$courseId/modules/items/$itemId'
    | '/api/canvas/courses/$courseId/files/$fileId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calendar'
    | '/todo'
    | '/courses'
    | '/api/trpc/$'
    | '/courses/$courseId/announcements'
    | '/courses/$courseId/assignments'
    | '/courses/$courseId/discussions'
    | '/courses/$courseId/files'
    | '/courses/$courseId/grades'
    | '/courses/$courseId/modules'
    | '/courses/$courseId/pages'
    | '/courses/$courseId/quizzes'
    | '/courses/$courseId/syllabus'
    | '/courses/$courseId/users'
    | '/courses/$courseId'
    | '/courses/$courseId/assignments/$assignmentId'
    | '/courses/$courseId/discussions/$topicId'
    | '/courses/$courseId/files/$fileId'
    | '/courses/$courseId/pages/$pageUrl'
    | '/courses/$courseId/quizzes/$quizId'
    | '/courses/$courseId/tools/$tabId'
    | '/courses/$courseId/modules/items/$itemId'
    | '/api/canvas/courses/$courseId/files/$fileId'
  id:
    | '__root__'
    | '/'
    | '/calendar'
    | '/courses'
    | '/todo'
    | '/courses/$courseId'
    | '/courses/'
    | '/api/trpc/$'
    | '/courses/$courseId/announcements'
    | '/courses/$courseId/assignments'
    | '/courses/$courseId/discussions'
    | '/courses/$courseId/files'
    | '/courses/$courseId/grades'
    | '/courses/$courseId/modules'
    | '/courses/$courseId/pages'
    | '/courses/$courseId/quizzes'
    | '/courses/$courseId/syllabus'
    | '/courses/$courseId/users'
    | '/courses/$courseId/'
    | '/courses/$courseId/assignments_/$assignmentId'
    | '/courses/$courseId/discussions_/$topicId'
    | '/courses/$courseId/files_/$fileId'
    | '/courses/$courseId/pages_/$pageUrl'
    | '/courses/$courseId/quizzes_/$quizId'
    | '/courses/$courseId/tools/$tabId'
    | '/courses/$courseId/modules_/items/$itemId'
    | '/api/canvas/courses/$courseId/files/$fileId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalendarRoute: typeof CalendarRoute
  CoursesRoute: typeof CoursesRouteWithChildren
  TodoRoute: typeof TodoRoute
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
  ApiCanvasCoursesCourseIdFilesFileIdRoute: typeof ApiCanvasCoursesCourseIdFilesFileIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/todo': {
      id: '/todo'
      path: '/todo'
      fullPath: '/todo'
      preLoaderRoute: typeof TodoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/': {
      id: '/courses/'
      path: '/'
      fullPath: '/courses/'
      preLoaderRoute: typeof CoursesIndexRouteImport
      parentRoute: typeof CoursesRoute
    }
    '/courses/$courseId': {
      id: '/courses/$courseId'
      path: '/$courseId'
      fullPath: '/courses/$courseId'
      preLoaderRoute: typeof CoursesCourseIdRouteImport
      parentRoute: typeof CoursesRoute
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$courseId/': {
      id: '/courses/$courseId/'
      path: '/'
      fullPath: '/courses/$courseId/'
      preLoaderRoute: typeof CoursesCourseIdIndexRouteImport
      parentRoute: typeof CoursesCourseIdRoute
    }
    '/courses/$courseId/announcements': {
      id: '/courses/$courseId/announcements'
      path: '/announcements'
      fullPath: '/courses/$courseId/announcements'
      preLoaderRoute: typeof CoursesCourseIdAnnouncementsRouteImport
      parentRoute: typeof CoursesCourseIdRoute
    }
    '/courses/$courseId/assignments': {
      id: '/courses/$courseId/assignments'
      path: '/assignments'
      fullPath: '/courses/$courseId/assignments'
      preLoaderRoute: typeof CoursesCourseIdAssignmentsRouteImport
      parentRoute: typeof CoursesCourseIdRoute
    }
    '/courses/$courseId/discussions': {
      id: '/courses/$courseId/discussions'
      path: '/discussions'
      fullPath: '/courses/$courseId/discussions'
      preLoaderRoute: typeof CoursesCourseIdDiscussionsRouteImport
      parentRoute: typeof CoursesCourseIdRoute
    }
    '/courses/$courseId/files': {
      id: '/courses/$courseId/files'
      path: '/files'
      fullPath: '/courses/$courseId/files'
      preLoaderRoute: typeof CoursesCourseIdFilesRouteImport
      parentRoute: typeof CoursesCourseIdRoute
    }
    '/courses/$courseId/grades': {
      id: '/courses/$courseId/grades'
      path: '/grades'
      fullPath: '/courses/$courseId/grades'
      preLoaderRoute: typeof CoursesCourseIdGradesRouteImport
      parentRoute: typeof CoursesCourseIdRoute
    }
    '/courses/$courseId/modules': {
      id: '/courses/$courseId/modules'
      path: '/modules'
      fullPath: '/courses/$courseId/modules'
      preLoaderRoute: typeof CoursesCourseIdModulesRouteImport
      parentRoute: typeof CoursesCourseIdRoute
    }
    '/courses/$courseId/pages': {
      id: '/courses/$courseId/pages'
      path: '/pages'
      fullPath: '/courses/$courseId/pages'
      preLoaderRoute: typeof CoursesCourseIdPagesRouteImport
      parentRoute: typeof CoursesCourseIdRoute
    }
    '/courses/$courseId/quizzes': {
      id: '/courses/$courseId/quizzes'
      path: '/quizzes'
      fullPath: '/courses/$courseId/quizzes'
      preLoaderRoute: typeof CoursesCourseIdQuizzesRouteImport
      parentRoute: typeof CoursesCourseIdRoute
    }
    '/courses/$courseId/syllabus': {
      id: '/courses/$courseId/syllabus'
      path: '/syllabus'
      fullPath: '/courses/$courseId/syllabus'
      preLoaderRoute: typeof CoursesCourseIdSyllabusRouteImport
      parentRoute: typeof CoursesCourseIdRoute
    }
    '/courses/$courseId/users': {
      id: '/courses/$courseId/users'
      path: '/users'
      fullPath: '/courses/$courseId/users'
      preLoaderRoute: typeof CoursesCourseIdUsersRouteImport
      parentRoute: typeof CoursesCourseIdRoute
    }
    '/courses/$courseId/assignments_/$assignmentId': {
      id: '/courses/$courseId/assignments_/$assignmentId'
      path: '/assignments/$assignmentId'
      fullPath: '/courses/$courseId/assignments/$assignmentId'
      preLoaderRoute: typeof CoursesCourseIdAssignmentsAssignmentIdRouteImport
      parentRoute: typeof CoursesCourseIdRoute
    }
    '/courses/$courseId/discussions_/$topicId': {
      id: '/courses/$courseId/discussions_/$topicId'
      path: '/discussions/$topicId'
      fullPath: '/courses/$courseId/discussions/$topicId'
      preLoaderRoute: typeof CoursesCourseIdDiscussionsTopicIdRouteImport
      parentRoute: typeof CoursesCourseIdRoute
    }
    '/courses/$courseId/files_/$fileId': {
      id: '/courses/$courseId/files_/$fileId'
      path: '/files/$fileId'
      fullPath: '/courses/$courseId/files/$fileId'
      preLoaderRoute: typeof CoursesCourseIdFilesFileIdRouteImport
      parentRoute: typeof CoursesCourseIdRoute
    }
    '/courses/$courseId/pages_/$pageUrl': {
      id: '/courses/$courseId/pages_/$pageUrl'
      path: '/pages/$pageUrl'
      fullPath: '/courses/$courseId/pages/$pageUrl'
      preLoaderRoute: typeof CoursesCourseIdPagesPageUrlRouteImport
      parentRoute: typeof CoursesCourseIdRoute
    }
    '/courses/$courseId/quizzes_/$quizId': {
      id: '/courses/$courseId/quizzes_/$quizId'
      path: '/quizzes/$quizId'
      fullPath: '/courses/$courseId/quizzes/$quizId'
      preLoaderRoute: typeof CoursesCourseIdQuizzesQuizIdRouteImport
      parentRoute: typeof CoursesCourseIdRoute
    }
    '/courses/$courseId/tools/$tabId': {
      id: '/courses/$courseId/tools/$tabId'
      path: '/tools/$tabId'
      fullPath: '/courses/$courseId/tools/$tabId'
      preLoaderRoute: typeof CoursesCourseIdToolsTabIdRouteImport
      parentRoute: typeof CoursesCourseIdRoute
    }
    '/courses/$courseId/modules_/items/$itemId': {
      id: '/courses/$courseId/modules_/items/$itemId'
      path: '/modules/items/$itemId'
      fullPath: '/courses/$courseId/modules/items/$itemId'
      preLoaderRoute: typeof CoursesCourseIdModulesItemsItemIdRouteImport
      parentRoute: typeof CoursesCourseIdRoute
    }
    '/api/canvas/courses/$courseId/files/$fileId': {
      id: '/api/canvas/courses/$courseId/files/$fileId'
      path: '/api/canvas/courses/$courseId/files/$fileId'
      fullPath: '/api/canvas/courses/$courseId/files/$fileId'
      preLoaderRoute: typeof ApiCanvasCoursesCourseIdFilesFileIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CoursesCourseIdRouteChildren {
  CoursesCourseIdAnnouncementsRoute: typeof CoursesCourseIdAnnouncementsRoute
  CoursesCourseIdAssignmentsRoute: typeof CoursesCourseIdAssignmentsRoute
  CoursesCourseIdDiscussionsRoute: typeof CoursesCourseIdDiscussionsRoute
  CoursesCourseIdFilesRoute: typeof CoursesCourseIdFilesRoute
  CoursesCourseIdGradesRoute: typeof CoursesCourseIdGradesRoute
  CoursesCourseIdModulesRoute: typeof CoursesCourseIdModulesRoute
  CoursesCourseIdPagesRoute: typeof CoursesCourseIdPagesRoute
  CoursesCourseIdQuizzesRoute: typeof CoursesCourseIdQuizzesRoute
  CoursesCourseIdSyllabusRoute: typeof CoursesCourseIdSyllabusRoute
  CoursesCourseIdUsersRoute: typeof CoursesCourseIdUsersRoute
  CoursesCourseIdIndexRoute: typeof CoursesCourseIdIndexRoute
  CoursesCourseIdAssignmentsAssignmentIdRoute: typeof CoursesCourseIdAssignmentsAssignmentIdRoute
  CoursesCourseIdDiscussionsTopicIdRoute: typeof CoursesCourseIdDiscussionsTopicIdRoute
  CoursesCourseIdFilesFileIdRoute: typeof CoursesCourseIdFilesFileIdRoute
  CoursesCourseIdPagesPageUrlRoute: typeof CoursesCourseIdPagesPageUrlRoute
  CoursesCourseIdQuizzesQuizIdRoute: typeof CoursesCourseIdQuizzesQuizIdRoute
  CoursesCourseIdToolsTabIdRoute: typeof CoursesCourseIdToolsTabIdRoute
  CoursesCourseIdModulesItemsItemIdRoute: typeof CoursesCourseIdModulesItemsItemIdRoute
}

const CoursesCourseIdRouteChildren: CoursesCourseIdRouteChildren = {
  CoursesCourseIdAnnouncementsRoute: CoursesCourseIdAnnouncementsRoute,
  CoursesCourseIdAssignmentsRoute: CoursesCourseIdAssignmentsRoute,
  CoursesCourseIdDiscussionsRoute: CoursesCourseIdDiscussionsRoute,
  CoursesCourseIdFilesRoute: CoursesCourseIdFilesRoute,
  CoursesCourseIdGradesRoute: CoursesCourseIdGradesRoute,
  CoursesCourseIdModulesRoute: CoursesCourseIdModulesRoute,
  CoursesCourseIdPagesRoute: CoursesCourseIdPagesRoute,
  CoursesCourseIdQuizzesRoute: CoursesCourseIdQuizzesRoute,
  CoursesCourseIdSyllabusRoute: CoursesCourseIdSyllabusRoute,
  CoursesCourseIdUsersRoute: CoursesCourseIdUsersRoute,
  CoursesCourseIdIndexRoute: CoursesCourseIdIndexRoute,
  CoursesCourseIdAssignmentsAssignmentIdRoute:
    CoursesCourseIdAssignmentsAssignmentIdRoute,
  CoursesCourseIdDiscussionsTopicIdRoute:
    CoursesCourseIdDiscussionsTopicIdRoute,
  CoursesCourseIdFilesFileIdRoute: CoursesCourseIdFilesFileIdRoute,
  CoursesCourseIdPagesPageUrlRoute: CoursesCourseIdPagesPageUrlRoute,
  CoursesCourseIdQuizzesQuizIdRoute: CoursesCourseIdQuizzesQuizIdRoute,
  CoursesCourseIdToolsTabIdRoute: CoursesCourseIdToolsTabIdRoute,
  CoursesCourseIdModulesItemsItemIdRoute:
    CoursesCourseIdModulesItemsItemIdRoute,
}

const CoursesCourseIdRouteWithChildren = CoursesCourseIdRoute._addFileChildren(
  CoursesCourseIdRouteChildren,
)

interface CoursesRouteChildren {
  CoursesCourseIdRoute: typeof CoursesCourseIdRouteWithChildren
  CoursesIndexRoute: typeof CoursesIndexRoute
}

const CoursesRouteChildren: CoursesRouteChildren = {
  CoursesCourseIdRoute: CoursesCourseIdRouteWithChildren,
  CoursesIndexRoute: CoursesIndexRoute,
}

const CoursesRouteWithChildren =
  CoursesRoute._addFileChildren(CoursesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalendarRoute: CalendarRoute,
  CoursesRoute: CoursesRouteWithChildren,
  TodoRoute: TodoRoute,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
  ApiCanvasCoursesCourseIdFilesFileIdRoute:
    ApiCanvasCoursesCourseIdFilesFileIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
